services:
  go2rtc:
    image: alexxit/go2rtc
    ports:
      - "1984:1984"         # WebUI and API
      # - "8554:8554"         # RTSP
      - "8555:8555"         # webrtc
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=America/Chicago  # timezone in logs